### ISSUE TITLE
Forcing Content-Type to text/javascript

### ISSUE THREAD

**Issue by davethehat** [gustavnikolaj/express-jsxtransform#5]
While upgrading dependencies and testing one of our systems I found all calls were returning a Content-Type of text/javascript. The jsxtransform middleware appears to be doing this to all requests:

```javascript
            intercept: function (body, send) {
                var annotationInserted = false;

                if (res.statusCode === 200) {

                // ...

                    res.setHeader('Content-Type', 'text/javascript');
                    res.setHeader('Content-Length', Buffer.byteLength(body));
                    send(body);
                }
```

Am I missing something, or is this a bug?

**Comment by gustavnikolaj** [comment]
Seems somewhat related to this issue https://github.com/papandreou/express-compiless/pull/12 from a project also using express-interceptor. 

I'll look into a fix for this as soon as I get time. Hopefully tonight.

**Comment by gustavnikolaj** [comment]
Released a new version 3.0.1 with this fix in it.

**Comment by gustavnikolaj** [comment]
Sorry for the inconvenience.

**Comment by davethehat** [comment]
Thanks for the fix - appreciated!
